# Site Settings
title: Wisdom of a grain of sand - Nguyen Chien Cong
email: nguyen.chiencong@gmail.com
tagline: Wisdom of a grain of sand (2023) | A philosophy book on the nature of the self.
description: >
  Wisdom of a grain of sand (2023) is a philosophical and psychological inquiry on the nature of the self. It leads the reader through various existential questions that one might ask if one is really serious about life.
baseurl: ""
url: "http://nguyenchiencong.github.io"
github_username:  nguyenchiencong
# Build Settings
plugins:
  - jekyll-seo-tag
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM